name: CI/CD Pipeline with EKS and Flask

on:
  push:
    branches:
      - main  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
    # 4. Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 5. Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 6. Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: 123012261664.dkr.ecr.AWS_REGION.amazonaws.com
      env:
        AWS_REGION: AWS_REGION

    # 7. Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t 123012261664.dkr.ecr.AWS_REGION.amazonaws.com/my-flask-repo:$GITHUB_SHA .
        docker tag 123012261664.dkr.ecr.AWS_REGION.amazonaws.com/my-flask-repo:$GITHUB_SHA 123012261664.dkr.ecr.AWS_REGION.amazonaws.com/my-flask-repo:latest
        docker push 123012261664.dkr.ecr.AWS_REGION.amazonaws.com/my-flask-repo:$GITHUB_SHA
        docker push 123012261664.dkr.ecr.AWS_REGION.amazonaws.com/my-flask-repo:latest

    # 8. Deploy to EKS using kubectl
    - name: Deploy to EKS using kubectl
      env:
        AWS_REGION: AWS_REGION
        EKS_CLUSTER_NAME: mataz-cluster
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        echo "$KUBE_CONFIG" > kubeconfig.yaml
        aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION --kubeconfig kubeconfig.yaml
        kubectl --kubeconfig kubeconfig.yaml apply -f deployment.yaml
        kubectl --kubeconfig kubeconfig.yaml apply -f service.yaml
        kubectl rollout restart deployment my-flask-app --kubeconfig kubeconfig.yaml
